CREATE TABLE compartimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(2) NOT NULL UNIQUE,
    tipo_atual VARCHAR(20),
    ultimo_tipo_armazenado VARCHAR(20),
    quantidade_atual NUMERIC(10, 3) NOT NULL DEFAULT 0,
    ultima_data_armazenamento DATE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    versao BIGINT
);

CREATE TABLE ingredientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    quantidade NUMERIC(10, 3) NOT NULL,
    compartimento_id BIGINT NOT NULL,
    responsavel_ultima_movimentacao VARCHAR(100) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_ingredientes_compartimento
        FOREIGN KEY (compartimento_id)
        REFERENCES compartimentos(id)
);

CREATE TABLE historico_movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo_operacao VARCHAR(20) NOT NULL,
    quantidade NUMERIC(10, 3) NOT NULL,
    tipo_ingrediente VARCHAR(20) NOT NULL,
    nome_ingrediente VARCHAR(120) NOT NULL,
    responsavel VARCHAR(100) NOT NULL,
    compartimento_id BIGINT NOT NULL,
    ingrediente_id BIGINT,

    CONSTRAINT fk_historico_compartimento
        FOREIGN KEY (compartimento_id)
        REFERENCES compartimentos(id),

    CONSTRAINT fk_historico_ingrediente
        FOREIGN KEY (ingrediente_id)
        REFERENCES ingredientes(id)
);

CREATE INDEX idx_ingredientes_tipo ON ingredientes(tipo);
CREATE INDEX idx_ingredientes_compartimento ON ingredientes(compartimento_id);
CREATE INDEX idx_historico_data_hora ON historico_movimentacoes(data_hora);
CREATE INDEX idx_historico_compartimento ON historico_movimentacoes(compartimento_id);
CREATE INDEX idx_historico_tipo_ingrediente ON historico_movimentacoes(tipo_ingrediente);